version: "3"

services:
 #MongoDb
  mongodb:
    container_name: "mongo"
    image: mongo:latest
    restart: always
    volumes:
      - mongodb:/data/db

  web:
    build: .
    ports: 
      - "3000:3000"
    environment:
      - PORT=3000
      - DB_URI:mongodb://mongodb:27017
    depends_on:
      - mongodb

volumes:
  mongodb: {}