version: "3"

services:
 #MongoDb
  mongodb:
    container_name: "mongo_container"
    image: mongo:latest
    restart: always
    volumes:
      - mongodb:/data/db

  web:
    build: .
    ports: 
      - 3000
    depends_on:
      - mongodb

volumes:
  mongodb: 