
name: Simple Automated Continuous Integration

on:
  push:
    branches: ["main"]

jobs:
  print_message:
    runs-on: ubuntu-latest

    steps:
      - name: Automation practice
        run: npm test
